export const WEBSOCKET_MESSAGE = 'REDUX_WEBSOCKET::MESSAGE';
export const WEBSOCKET_OPEN = 'REDUX_WEBSOCKET::OPEN';
export const WEBSOCKET_CLOSED = 'REDUX_WEBSOCKET::CLOSED';
export const WEBSOCKET_CONNECT = 'REDUX_WEBSOCKET::CONNECT';
export const WEBSOCKET_DISCONNECT = 'REDUX_WEBSOCKET::DISCONNECT';
